### ISSUE TITLE
globalCount() is not working + required parameter

### ISSUE THREAD

**Issue by VictorVelarde** [CartoDB/carto-vl#1032]
### `globalCount` is not working

It returns `CartoValidationError: [Missing required property]: Metadata count for property pop_max is not defined` (using `pop_max`from populated_places dataset, but also trying with some other existing properties)

It can be tested at editor/index.html adding
`#eyJhIjoic3BlbmRfZGF0YSIsImIiOiIiLCJjIjoiY2FydG92bCIsImQiOiJodHRwczovL3t1c2VyfS5jYXJ0by5jb20iLCJlIjoid2lkdGg6IDdcbmNvbG9yOiBoc3YoJGNhdGVnb3J5LCAwLjcsIDEuKVxuQGdfY291bnQ6IGdsb2JhbENvdW50KCRjYXRlZ29yeSkiLCJmIjp7ImxuZyI6Mi4xNywibGF0Ijo0MS4zOH0sImciOjEzLCJoIjoiRGFya01hdHRlciIsImkiOiJkYXRhc2V0In0=`

---
### Unneeded parameter
On the other hand, it looks like it doesn't make sense to ask for a **property** as a parameter, as this  just returns a global count of features. So`@count: globalCount($pop_max)` should be probably just `@count: globalCount()`.

That very same improvement should be applied to viewport: 
`@count: viewportCount($pop_max)` should be just `@count: viewportCount()` [in this case there is a workaround: calculating `viewportFeatures()` length]

UPDATE: From https://github.com/CartoDB/carto-vl/pull/1011 it seems that viewportCount() works 
 currently without properties too (despite of that not being expected according to the API definition).

**Comment by Captain-Oski** [comment]
Is this issue currently resolved in the 0.9.1 ? 

Because I experience the same behavior.

Impossible to make globalCount() or globalCount($cartodb_id) or any field working.

But viewportCount() works like a charm.

![undefined](https://user-images.githubusercontent.com/7432894/47400242-66414b00-d70a-11e8-9126-4cb702287afa.PNG)

Thank you.

**Comment by davidmanzanares** [comment]
Sorry, we close the issues when they are fixed in `master`, not when they make it to a release.

In this case, the fix is in `master` but currently, there is no release with it. The next release will have it.

You can see the Changelog here: https://github.com/CartoDB/carto-vl/blob/master/CHANGELOG.md
