### ISSUE TITLE
Reduce number of examples

### ISSUE THREAD

**Issue by davidmanzanares** [CartoDB/carto-vl#1036]
## Context

We have been improving the examples for a while, adding lots of examples. But some examples should probably be removed.

I have seen 3 issues:
- Orphan examples that are not referenced anywhere (sometimes those should be moved to `debug/`
- Duplicated examples. Maybe it's not identical, but it may not make sense to keep it anyway
- Unrecommended practices. Every example should show expected usage, not corner cases nor borderline API usage
- General style and design. I've seen examples with calls to `alert()`

---

## Examples list

_Updated_

❌  misc/edit-sql-expressions.html
❌  misc/legends/legend-numeric-chart.html
❌  misc/legends/legend-image.html
❌  misc/legends/legend-classifier.html
❌  misc/legends/legend-top.html
❌  misc/legends/legend-buckets.html
❌  misc/legends/legend-lines.html
❌  misc/legends/legend-polygon.html
❌  misc/legends/legend-categorical-chart.html
❌  misc/legends/legend-base.html
❌  misc/legends/legend-number.html
❌  misc/legends/legend-stroke.html
❌  misc/legends/poly-legend-ma.html
❌  misc/populated-places.html
❌  misc/widgets/viewportAgg.html
❌  basics/boilerplate.html
✅  basics/add-layer.html
✅  basics/query-layer.html
✅  basics/multiple-layers.html
✅  basics/basic-style.html
✅  basics/browser-support.html
✅  basics/select-layer.html
✅  advanced/hurricane-harvey.html
✅  advanced/us-population-by-county.html
❌  advanced/interactive-filter.html
✅  advanced/landing-page/hurricane-harvey.html
❌  advanced/landing-page/detroit-development.html
❌  advanced/landing-page/rivers.html
❌  advanced/landing-page/spend-data.html
❌  advanced/landing-page/us-population-by-country.html
❌  advanced/denver-trees.html
✅  advanced/taxi-pickups.html
✅  advanced/ocean-bathymetry.html
✅  advanced/classification-variables.html
✅  advanced/external-geojson.html
✅  basemap/pitch-bearing.html
✅  basemap/basemap-labels-on-top.html
✅  basemap/basemap-labels-under.html
✅  basemap/color-map-background.html
✅  basemap/project-layer.html
✅  index.html
✅  legends/choropleth-legend.html
✅  legends/category-line-legend.html
✅  legends/image-legend.html
✅  legends/unclassed-point-legend.html
✅  legends/category-point-legend.html
✅  legends/feature-and-legend-opacity.html
✅  labeling/point-labels-size-zoom.html
✅  labeling/polygon-labels.html
✅  labeling/point-labels.html
✅  labeling/point-labels-conditional-style.html
✅  labeling/cluster-labels-average.html
✅  labeling/cluster-labels-count.html
✅  interactivity/hover.html
❌  interactivity/interactive-images.html
✅  interactivity/interactive-based-styling.html
✅  interactivity/pop-ups.html
✅  interactivity/click.html
❌  interactivity/enter-leave.html
❌  interactivity/histogram.html
✅  interactivity/animation-controls.html
✅  interactivity/interact-multiple-layers.html
✅  guides/add-legends/step-3.html
❌  guides/add-legends/step-2.html
✅  guides/add-legends/step-5.html
✅  guides/add-legends/step-9.html
✅  guides/add-legends/step-8.html
✅  guides/add-legends/step-10.html
✅  guides/add-legends/step-4.html
✅  guides/add-legends/step-7.html
✅  guides/add-legends/step-6.html
✅  guides/add-legends/step-1.html
✅  guides/style-with-expressions/step-3.html
✅  guides/style-with-expressions/step-2.html
✅  guides/style-with-expressions/step-1.html
✅  guides/animated-viz/step-3.html
✅  guides/animated-viz/step-2.html
✅  guides/animated-viz/step-5.html
✅  guides/animated-viz/step-4.html
✅  guides/animated-viz/step-7.html
❌  guides/animated-viz/step-6.html
✅  guides/animated-viz/step-1.html
✅  guides/animated-viz/step-0.html
✅  guides/aggregation-and-data-summaries/step-3.html
✅  guides/aggregation-and-data-summaries/step-2.html
✅  guides/aggregation-and-data-summaries/step-1.html
✅  guides/zoom-based-styles/step-3.html
✅  guides/zoom-based-styles/step-2.html
✅  guides/zoom-based-styles/step-5.html
✅  guides/zoom-based-styles/step-8.html
✅  guides/zoom-based-styles/step-4.html
✅  guides/zoom-based-styles/step-7.html
✅  guides/zoom-based-styles/step-6.html
✅  guides/zoom-based-styles/step-1.html
✅  guides/data-driven-viz-1/step-3.html
✅  guides/data-driven-viz-1/step-2.html
✅  guides/data-driven-viz-1/step-5.html
✅  guides/data-driven-viz-1/step-9.html
✅  guides/data-driven-viz-1/step-8.html
✅  guides/data-driven-viz-1/step-4.html
✅  guides/data-driven-viz-1/step-7.html
✅  guides/data-driven-viz-1/step-6.html
✅  guides/data-driven-viz-1/step-1.html
❌  guides/image-files/external-image.html
❌  guides/image-files/align-image.html
❌  guides/image-files/category-to-image.html
❌  guides/image-files/color-image.html
❌  guides/image-files/color-category-image.html
❌  guides/image-files/built-in-image.html
✅  guides/getting-started/step-2.html
✅  guides/getting-started/step-1.html
✅  guides/add-interactivity/step-3.html
✅  guides/add-interactivity/step-2.html
✅  guides/add-interactivity/step-4.html
❌  guides/add-interactivity/step-1.html
✅  guides/add-data-sources/step-3.html
✅  guides/add-data-sources/step-2.html
✅  guides/add-data-sources/step-1.html
✅  guides/add-widgets/step-3.html
✅  guides/add-widgets/step-2.html
✅  guides/add-widgets/step-1.html
✅  guides/build-custom-charts/step-3.html
✅  guides/build-custom-charts/step-2.html
✅  guides/build-custom-charts/step-5.html
✅  guides/build-custom-charts/step-4.html
✅  guides/build-custom-charts/step-6.html
✅  guides/build-custom-charts/step-1.html
❌  guides/interpolation/step-2.html
❌  guides/interpolation/step-1.html
❌  guides/interpolation/step-0.html
✅  guides/data-driven-viz-2/step-3.html
✅  guides/data-driven-viz-2/step-2.html
✅  guides/data-driven-viz-2/step-4.html
✅  guides/data-driven-viz-2/step-1.html
✅  styling/style-with-variables.html
✅  styling/color-schemes.html
✅  styling/image-external.html
✅  styling/draw-order.html
✅  styling/animation.html
✅  styling/style-by-number.html
✅  styling/style-by-category.html
✅  styling/image-multiple.html
✅  styling/viewport.html
✅  styling/image-single.html
✅  styling/color-spaces.html
✅  styling/scaled.html
✅  styling/filter.html
❌  sources/MVT.html
❌  sources/GeoJSON.html
❌  editor/redirect.html
✅  editor/index.html
✅  widgets/histogram-widget-viewport.html
✅  widgets/category-widget-viewport.html
✅  widgets/numeric-chart.html
✅  widgets/viewport-summary.html
✅  widgets/category-chart.html
✅  widgets/weighted-histogram.html
❌  widgets/histogram/category-histogram.html
❌  widgets/histogram/numeric-histogram.html

**Comment by rochoa** [comment]
In order to detect non-referenced examples, I just used the following bash command:

```sh
for example in $(find examples -name '*.html' | sed 's/^examples\///g'); do
    ag $example > /dev/null;
    if [ $? -eq 0 ]; then
        echo "✅  $example"
    else
        echo "❌  $example"
    fi
done
```

## Result
Most of the examples seem to be referenced either in the guides or in the examples.
The major issues:
 1. The `misc` directory examples (especially the legends ones), followed by
 1. some `advanced` examples, and
 1. some `guides` examples that seem to be no longer in use.

### Actions
I would:
 1. Review if some of those examples could be incorporated to the Developers website examples in the proper category. Othewise, remove them or move them to the debug directory.
 1. Pretty much the same approach.
 1. Remove them.
 1. Remove any non-referenced example that is not working or required extra work.

The other option is to keep all of them without any futher action.

@VictorVelarde, what do you think?

### Complete list
❌  advanced/denver-trees.html
✅  advanced/external-geojson.html
✅  advanced/hurricane-harvey.html
❌  advanced/landing-page/detroit-development.html
✅  advanced/landing-page/hurricane-harvey.html
❌  advanced/landing-page/rivers.html
❌  advanced/landing-page/spend-data.html
❌  advanced/landing-page/us-population-by-country.html
✅  advanced/ocean-bathymetry.html
✅  advanced/taxi-pickups.html
✅  advanced/us-population-by-county.html
✅  basemap/basemap-labels-on-top.html
✅  basemap/basemap-labels-under.html
✅  basemap/color-map-background.html
✅  basemap/pitch-bearing.html
✅  basemap/project-layer.html
✅  basics/add-layer.html
✅  basics/basic-style.html
❌  basics/boilerplate.html
✅  basics/browser-support.html
✅  basics/multiple-layers.html
✅  basics/query-layer.html
✅  basics/select-layer.html
✅  editor/index.html
❌  editor/redirect.html
✅  guides/add-data-sources/step-1.html
✅  guides/add-data-sources/step-2.html
✅  guides/add-data-sources/step-3.html
❌  guides/add-interactivity/step-1.html
✅  guides/add-interactivity/step-2.html
✅  guides/add-interactivity/step-3.html
✅  guides/add-interactivity/step-4.html
✅  guides/add-legends/step-1.html
❌  guides/add-legends/step-10.html
❌  guides/add-legends/step-2.html
✅  guides/add-legends/step-3.html
✅  guides/add-legends/step-4.html
✅  guides/add-legends/step-5.html
✅  guides/add-legends/step-6.html
✅  guides/add-legends/step-7.html
✅  guides/add-legends/step-8.html
✅  guides/add-legends/step-9.html
✅  guides/add-widgets/step-1.html
✅  guides/add-widgets/step-2.html
✅  guides/add-widgets/step-3.html
✅  guides/aggregation-and-data-summaries/step-1.html
✅  guides/aggregation-and-data-summaries/step-2.html
✅  guides/aggregation-and-data-summaries/step-3.html
✅  guides/animated-viz/step-0.html
✅  guides/animated-viz/step-1.html
✅  guides/animated-viz/step-2.html
✅  guides/animated-viz/step-3.html
✅  guides/animated-viz/step-4.html
✅  guides/animated-viz/step-5.html
❌  guides/animated-viz/step-6.html
✅  guides/animated-viz/step-7.html
✅  guides/data-driven-viz-1/step-1.html
✅  guides/data-driven-viz-1/step-2.html
✅  guides/data-driven-viz-1/step-3.html
✅  guides/data-driven-viz-1/step-4.html
✅  guides/data-driven-viz-1/step-5.html
✅  guides/data-driven-viz-1/step-6.html
✅  guides/data-driven-viz-1/step-7.html
✅  guides/data-driven-viz-1/step-8.html
✅  guides/data-driven-viz-1/step-9.html
✅  guides/data-driven-viz-2/step-1.html
✅  guides/data-driven-viz-2/step-2.html
✅  guides/data-driven-viz-2/step-3.html
✅  guides/data-driven-viz-2/step-4.html
✅  guides/getting-started/step-1.html
✅  guides/getting-started/step-2.html
❌  guides/image-files/align-image.html
❌  guides/image-files/built-in-image.html
❌  guides/image-files/category-to-image.html
❌  guides/image-files/color-category-image.html
❌  guides/image-files/color-image.html
❌  guides/image-files/external-image.html
❌  guides/interpolation/step-0.html
❌  guides/interpolation/step-1.html
❌  guides/interpolation/step-2.html
✅  guides/style-with-expressions/step-1.html
✅  guides/style-with-expressions/step-2.html
✅  guides/style-with-expressions/step-3.html
✅  guides/zoom-based-styles/step-1.html
✅  guides/zoom-based-styles/step-2.html
✅  guides/zoom-based-styles/step-3.html
✅  guides/zoom-based-styles/step-4.html
✅  guides/zoom-based-styles/step-5.html
✅  guides/zoom-based-styles/step-6.html
✅  guides/zoom-based-styles/step-7.html
✅  guides/zoom-based-styles/step-8.html
✅  index.html
✅  interactivity/animation-controls.html
✅  interactivity/click.html
❌  interactivity/enter-leave.html
❌  interactivity/histogram.html
✅  interactivity/hover.html
✅  interactivity/interact-multiple-layers.html
✅  interactivity/interactive-based-styling.html
❌  interactivity/interactive-images.html
✅  interactivity/pop-ups.html
✅  labeling/point-labels-conditional-style.html
✅  labeling/point-labels-size-zoom.html
✅  labeling/point-labels.html
✅  labeling/polygon-labels.html
✅  legends/category-line-legend.html
✅  legends/category-point-legend.html
✅  legends/choropleth-legend.html
✅  legends/feature-and-legend-opacity.html
✅  legends/image-legend.html
✅  legends/unclassed-point-legend.html
❌  misc/edit-sql-expressions.html
❌  misc/legends/legend-base.html
❌  misc/legends/legend-buckets.html
❌  misc/legends/legend-categorical-chart.html
❌  misc/legends/legend-classifier.html
❌  misc/legends/legend-image.html
❌  misc/legends/legend-lines.html
❌  misc/legends/legend-number.html
❌  misc/legends/legend-numeric-chart.html
❌  misc/legends/legend-polygon.html
❌  misc/legends/legend-stroke.html
❌  misc/legends/legend-top.html
❌  misc/legends/poly-legend-ma.html
❌  misc/populated-places.html
❌  misc/widgets/viewportAgg.html
❌  sources/GeoJSON.html
❌  sources/MVT.html
✅  styling/animation.html
✅  styling/color-schemes.html
✅  styling/color-spaces.html
✅  styling/draw-order.html
✅  styling/filter.html
✅  styling/image-external.html
✅  styling/image-multiple.html
✅  styling/image-single.html
✅  styling/scaled.html
✅  styling/style-by-category.html
✅  styling/style-by-number.html
✅  styling/style-with-variables.html
✅  styling/viewport.html
✅  widgets/category-chart.html
✅  widgets/category-widget-viewport.html
✅  widgets/histogram-widget-viewport.html
✅  widgets/numeric-chart.html
✅  widgets/viewport-summary.html
✅  widgets/weighted-histogram.html

**Comment by VictorVelarde** [comment]
Great list!

Once you have made the effort to find these ones, I would definitively go for it.

I would specially check 2 groups:
* **advanced/landing-page/**. As this 'landing' was finally not created, we are missing some interesting examples, such as `denver-trees.html`, so I would move them to `advanced` root.
* **guides**. Probably orphans  are not needed anymore there, but there might be a "missing step" somewhere, so I would review them & delete if they are not needed.

Regarding to the rest, I would check if `editor/redirect.html` is somehow used internally and just delete the rest.

It would be great if @makella could have a look at this process when she's back, cause she has worked a lot in organizing this. If not, I would review them myself at the end of the cycle.

**Comment by rochoa** [comment]
Let's wait for @makella, I can work with her when she is back.

**Comment by makella** [comment]
heyyy nice review here! shows where we have some cleaning up to do... taking a closer look now (mostly to refresh my memory after the past 3 weeks! 😄)

**Comment by makella** [comment]
Ok,

I definitely agree that we should consolidate here. 

To give a better understanding of what's going on (for the most part): 
- is that anything that we didn't want to "show" on the Dev Center was not referenced in `examples.json` but also not removed. For example, ❌`interactivity/interactive-images.html` is a good example, but is not referenced because of a bug that needs to be fixed. There are other cases where yes, we need to definitely remove, move, clean-up.
- The `misc` folder was functioning as a "test/enhance before making public" area that I would use with David and Elena. See notes below.
- Should the Editor files be in the examples folder?

I did an initial review below. I am totally willing to clean this up and take on the organizational part. In addition, there are several new examples that I want to add so it would be good to get this cleaned up/organized with proper sections, get deprecated stuff consolidated and start with new examples after that point.


❌ advanced/denver-trees.html
- I think at the time this was "advanced" not so much anymore... and we can probably remove since there is a screenshot of this map (not live embed) on [the main VL Dev Center page](https://carto.com/developers/carto-vl/) under the Guides section


❌ advanced/landing-page/detroit-development.html 
❌ advanced/landing-page/rivers.html
❌ advanced/landing-page/spend-data.html
❌ advanced/landing-page/us-population-by-country.html
- Initially, the maps in `landing-page` were meant to directly serve www.carto.com/engine so they wouldn't break. It looks like those maps live independently in the [website repo](https://github.com/CartoDB/website/tree/master/_app/engine/cartovl-examples). Rather than deleting, I would prever to look through and consider some for advanced styling and/or other example sections. For example, detroit-development could be used inside of an Animation examples section.


✅ advanced/landing-page/hurricane-harvey.html
- Needs to be moved out of landing-page since it is in advanced examples section.

✅ advanced/ocean-bathymetry.html
✅ advanced/taxi-pickups.html
✅ advanced/us-population-by-county.html
- For the "advanced" examples section, I think we can do some modifications. This is a larger conversation about the Styling section and overall organization.

❌ basics/boilerplate.html
- Should be deleted

✅ editor/index.html
❌ editor/redirect.html
- Editor files should probably be moved to a different location (?).

❌ guides/add-interactivity/step-1.html
❌ guides/add-legends/step-10.html
❌ guides/add-legends/step-2.html
- Let me take a closer look through these two guides to double check what's going on. @VictorVelarde in hindsight, wondering if the `step-` is getting confusing (well, it has been for me I've realized).

❌ guides/image-files/align-image.html
❌ guides/image-files/built-in-image.html
❌ guides/image-files/category-to-image.html
❌ guides/image-files/color-category-image.html
❌ guides/image-files/color-image.html
❌ guides/image-files/external-image.html
❌ guides/interpolation/step-0.html
❌ guides/interpolation/step-1.html
❌ guides/interpolation/step-2.html
- These are from Beta guides, should move to same location as other deprecated guide maps. 

❌ interactivity/enter-leave.html
❌ interactivity/histogram.html
❌ interactivity/interactive-images.html
- I think interactive images should be exposed, enter-leave didn't make too much sense at Beta time so is an artifact of that. Let me do a more thorough review before deciding.

❌ misc/edit-sql-expressions.html
❌ misc/legends/legend-base.html
❌ misc/legends/legend-buckets.html
❌ misc/legends/legend-categorical-chart.html
❌ misc/legends/legend-classifier.html
❌ misc/legends/legend-image.html
❌ misc/legends/legend-lines.html
❌ misc/legends/legend-number.html
❌ misc/legends/legend-numeric-chart.html
❌ misc/legends/legend-polygon.html
❌ misc/legends/legend-stroke.html
❌ misc/legends/legend-top.html
❌ misc/legends/poly-legend-ma.html
❌ misc/populated-places.html
❌ misc/widgets/viewportAgg.html
- As mentioned above, a lot of this was giving me examples to modify/test for examples section. We could put in `debug` as @rochoa suggests. I will clean the repetitive ones (ones that we use in the legends and widgets examples section) so we aren't making duplicate copies of the same things. I didn't use all of these for those sections so those ones can be moved to debug or somewhere more appropriate.

❌ sources/GeoJSON.html
❌ sources/MVT.html
- Currently, we don't have a sources section in examples and some source examples are mixed in basics. Before removing, would like to consider the organization of the example headings and content more. Question here: I'm not sure why we aren't exposing the MVT source example. It has been like that for a while.

**Comment by makella** [comment]
@rochoa can we discuss https://github.com/CartoDB/website/issues/4358 as well? In addition to the different landing pages, we also should consider how to serve/manage VL maps for the blog.

**Comment by makella** [comment]
related to above: https://github.com/CartoDB/website/issues/4355

**Comment by makella** [comment]
As discussed today in our meeting, we will add a directory `website` to house VL example maps that are used in different parts of the website. 
major goal: keeping the versioning updated
potential downfall: examples are updated only when a new version is released

**Comment by makella** [comment]
taken care of in today's release more details at: https://github.com/CartoDB/carto-vl/pull/1297
