### ISSUE TITLE
Improve examples

### ISSUE THREAD

**Issue by davidmanzanares** [CartoDB/carto-vl#1037]
I saw some inconsistencies between examples:
- Different HTML `<head>` sections
- Different ways to put the same code and difference in comments

Regarding comments, I would also try to reduce them, particularly when they the explain obvious things like `<!-- Include Mapbox GL JS -->` just before the JS script tag aiming to the CDN.

I would use comments only for the CVL functionality, and without making obvious comments like "Create a new layer" for "new Layer()".

Some examples are relatively big, simple is better.

**Comment by VictorVelarde** [comment]
Regarding to comments, I think this is related to the examples for the guides (step-N.html files at examples/guides)

Those detailed comments, sometimes pretty obvious for a dev, were discussed with @makella and @elenatorro as they might be useful for beginners / non-dev.

**Comment by elenatorro** [comment]
Hi 👋 There's an ongoing task for the examples: https://github.com/CartoDB/carto-vl/issues/978. In the related PR https://github.com/CartoDB/carto-vl/pull/987, @makella is working on following conventions in every example.

You may think it is obvious and that we don't need them, but we decided to keep them because people tend to copy paste examples, and we wanted to keep consistency between them. There is also a note about that in the EPIC issue (https://github.com/CartoDB/carto-vl/issues/950), in the **Conventions** section. 

I would suggest to continue this discussion in the related issues and closing this one. I think there's no need to add more noise in the backlog.

**Comment by rochoa** [comment]
Let's continue the discussion over there.
