### ISSUE TITLE
ViewportFeatures doesn't work with NaN filter

### ISSUE THREAD

**Issue by padawannn** [CartoDB/carto-vl#1047]
This issue https://github.com/CartoDB/carto-vl/issues/997 has been corrected but now viewportFeatures function does not work correctly. ViewportFeatures is counting the hidden geometries and also returns some very strange values like -9007199254740992 when property doesn't exist.

You can check the console log in this example:
[index_nan.zip](https://github.com/CartoDB/carto-vl/files/2464518/index_nan.zip)

**Comment by alissarose** [comment]
thanks for putting this in the public release to-do's @rochoa 

I just want to add some urgency though because this remains a huge blocker for MRLI close-out on our side since this presents a serious bug for Windows users. LMK if there's anything that can be done on our side to help with this or if there's a workaround for Windows users 🙏

**Comment by davidmanzanares** [comment]
Should be fixed in `master` by https://github.com/CartoDB/carto-vl/pull/1048

However, keep in mind that API changes have been made: `isNaN` has been removed and superseded by `isNull`.
