### ISSUE TITLE
Add support for classification methods

### ISSUE THREAD

**Issue by davidmanzanares** [CartoDB/carto-vl#11]
Add support for:
Viewport:
- [x] quantiles
- [x] equalIntervals
- [x] std
- [ ] jenks (it can be a similar clustering algorithm)

Global:
- [x] quantiles
- [x] equalIntervals
- [x] std
- [ ] jenks (it can be a similar clustering algorithm)

For geometry types:
- [x] points
- [x] polygons
- [x] lines
NOTE: some of these items may not be critical, and they are very related to each other.

**Comment by davidmanzanares** [comment]
PoC deployed! https://cartodb.github.io/renderer-prototype/example/mapbox.html#eyJhIjoicG9wX2RlbnNpdHlfcG9pbnRzIiwiYiI6IjRkMjEyMzc1Mzg2YmFmMWEwOWJiODI2MDhjNjQ4MjE4OGRhM2E1YjAiLCJjIjoibWFtYXRhYWtlbGxhIiwiZCI6ImNhcnRvLmNvbSIsImUiOiJ3aWR0aDogem9vbSgpXG5jb2xvcjogcmFtcChxdWFudGlsZXMoJGRuLCA2KSwgcHJpc20pIiwiZiI6eyJsbmciOi0xMC44NDA3MjE0MDE0NTMyNjYsImxhdCI6NDAuMDY0MDU0MTU2NTcwOTZ9LCJnIjoxLjQ5MTcwMTcxODU5NzUzMjV9

**Comment by makella** [comment]
hey @davidmanzanares 

first, let's use a sequential color scheme! (hahaaaaa)
https://cartodb.github.io/renderer-prototype/example/mapbox.html#eyJhIjoicG9wX2RlbnNpdHlfcG9pbnRzIiwiYiI6IjRkMjEyMzc1Mzg2YmFmMWEwOWJiODI2MDhjNjQ4MjE4OGRhM2E1YjAiLCJjIjoibWFtYXRhYWtlbGxhIiwiZCI6ImNhcnRvLmNvbSIsImUiOiJ3aWR0aDogem9vbSgpXG5jb2xvcjogcmFtcChxdWFudGlsZXMoJGRuLCA2KSwgc3Vuc2V0KSIsImYiOnsibG5nIjotMTAuODQwNzIxNDAxNDUzMjY2LCJsYXQiOjQwLjA2NDA1NDE1NjU3MDk2fSwiZyI6MS40OTE3MDE3MTg1OTc1MzI1fQ==

- the biggest thing popping out to me is that the color scheme is being read in the opposite way... where light = high and dark = low
  - since we haven't implemented https://github.com/CartoDB/renderer-prototype/issues/33, assuming this is a bug

I made the same map in Builder:
https://team.carto.com/u/mamataakella/builder/56681557-38fc-49cb-afc6-07359e832e7a/embed

**Comment by makella** [comment]
oh! and let me look in the TurboCARTO viewer to get the break points for 6 classes with that data

**Comment by makella** [comment]
@davidmanzanares 

with the internal work being done on classification methods, I'm not sure if that would change the results from Builder (just as a FYI)

output CartoCSS, 6 classes, quantiles:

```
#layer {
  marker-width: 3;
  marker-fill: #f3e79b;
  [ dn > 50 ] {
    marker-fill: #fabc82;
  }
  [ dn > 73 ] {
    marker-fill: #f59280;
  }
  [ dn > 92 ] {
    marker-fill: #dc6f8e;
  }
  [ dn > 113 ] {
    marker-fill: #ab5b9e;
  }
  [ dn > 140 ] {
    marker-fill: #5c53a5;
  }
  marker-fill-opacity: 1;
  marker-allow-overlap: true;
  marker-line-width: 0;
  marker-line-color: #FFFFFF;
  marker-line-opacity: 1;
}
```

**Comment by davidmanzanares** [comment]
Well... The computed ones by this are: `54.163999999999994, 77.096, 95.114, 115.94, 141.914`

Not a big difference

**Comment by makella** [comment]
great!

so glad this is here now!! nice job, david :)

**Comment by makella** [comment]
@davidmanzanares oh! so are we reading color schemes in backwards? i can open a separate issue if you need

**Comment by makella** [comment]
@davidmanzanares as discussed yesterday the minimum classification methods we should have are:

- [ ] quantiles
- [ ] equal interval
- [ ] some sort of "optimal" (i.e. jenks)
- [ ] standard deviation

**Comment by makella** [comment]
@davidmanzanares 

@elenatorro and I are working through the color/interpolation logic of both category and numeric data, and it occurred to me that for manual classification, we should consider it as one of these methods, and name it accordingly.

Right now, we use `ramp(buckets($attribute,color))` for both numeric and categorical data. In my opinion, what would make more sense is to provide a separate method for manual classification like: `manual` or `bounds` or `breaks` or `stops`.

This will help us avoid the confusion of `buckets` for numeric data. For example, if you want to color a numeric attribute categorically, you would:

`ramp(buckets($number,[50,20,100,80]),[red,orange,yellow,green])`

on the other hand, if you want to make stops with custom ranges, we could have:

`ramp(bounds($number,[5,20,60,90]),sunset)`

This is common in other statistical mapping software where one of the classification method options here is just one:

<img width="482" alt="screen shot 2018-07-10 at 8 43 20 am" src="https://user-images.githubusercontent.com/1566273/42517608-596af592-841d-11e8-82c1-148135e39190.png">

**Comment by davidmanzanares** [comment]
I may be a lost but `ramp(buckets($attribute,color))` wasn't valid.

In fact `ramp(buckets($number,[50,20,100,80]),[red,orange,yellow,green])` is valid and `ramp(bounds($number,[5,20,60,90]),sunset)` is simply done with ramp(buckets($number,[5,20,60,90]),sunset)`, which makes more sense since the classification is the same, the only thing that changes is that the color is a cartocolor instead of a custom color palette, right?

**Comment by elenatorro** [comment]
I think `ramp(buckets($attribute, color))` was just an example, it means `ramp(buckets($attribute, [numeric/categorical]), [color array])` (am I right?)

I agree it would be nice to have another specific expression because I think it is easier to understand how it behaves depending on the parameters.

**Comment by makella** [comment]
so actually, I'm talking about two different map types. 

This would be a category map on a numeric attribute (the numbers could be sequential or not depends on what category buckets the user wants to color with which colors):

`ramp(buckets($number,[50,20,100,80]),[red,orange,yellow,green])` the numbers aren't sequentially ordered so 50 = red, 20 = orange, 100 = yellow, and 80 = green all other values would default to our category gray. 

or 

`ramp(buckets($number,[50,20,100,80]),prism)`

On the other hand, if I wanted to do manual classification, I would order sequentially and want to show ranges (classes) vs. the 1:1 mapping of `bucket` to color: 

`ramp(buckets($number,[5,20,60,90]),[black,white])`

or

`ramp(buckets($number,[5,20,60,90]),sunset)`

In TurboCARTO there is some differentiation:

If you want to make a **choropleth** map with a numeric value _and_ manual class breaks, you would do:

`ramp([homes], cartocolor(Sunset), (270, 1100, 5000, 10000), "<");`
  
- here, notice the `"<"`

If you want to make a **cateogry** map with a numeric value _and_  buckets, you would do:

`ramp([homes], cartocolor(Prism), (270, 577, 658, 1100, 1237, 1368, 2268, 2269, 2597, 3229), "=", category);`

  - here, notice the `"=", category`

**Comment by davidmanzanares** [comment]
Regarding map type 1 the problem I see there is that you have categorical data in a numeric form. I think we shouldn't try to work well with this. If the user has categorical data then the user should transform the data into categories.

Regarding map type 2, what I understand is that the current `buckets` is doing exactly that. Dividing the numeric input into a set of numerical ranges: [-Infinity, 5], (5,20], [20,60)...

**Comment by makella** [comment]
> If the user has categorical data then the user should transform the data into categories.

mmmmm, I don't _fully_ agree. Orderable data (1,2,3 = high, medium, low) or something like months (1-12), etc. can all be considered "categorical numbers"

**Comment by davidmanzanares** [comment]
Yes, sure, I agree on that numbers can represent orderable categorical data. But I don't agree that they must be in numeric form. Users can and should cast them to `string` before pushing it to CARTO VL.

**Comment by makella** [comment]
ohhhhkayyyyy :/ 

regardless, do you think it makes sense to use `buckets` (the word) for both categorical string-based mapping _and_ numeric-based mapping? especially since buckets works differently for the two?

**Comment by davidmanzanares** [comment]
Yes, sure, we can have new names to distinguish that. How would you name them?

Regarding the first map type problem. I see I haven't convinced you. From my point of view, everything will be much easier (for the API and for development) if we don't allow numbers to be treated as categories. But, clearly, you have a point there, having new names will be the first step to allow that in any case, so we could review this in the future.

**Comment by makella** [comment]
> having new names will be the first step to allow that in any case, so we could review this in the future.

YES! I totally think this is the best step to reduce confusion for users.

Some ideas for naming:
`manual` or `bounds` or `breaks` or `ranges` 
are ones that come to me off the top of my head

**Comment by davidmanzanares** [comment]
:+1: From your list, I think `breaks` and `ranges` are the best ones (more concise)

**Comment by makella** [comment]
since you're cool with us adding this (thank you!!), you choose the one you like best :)

**Comment by rochoa** [comment]
I created a miscommunication problem with this issue. I only wanted to implement the Standard Deviation expression/classification method. I see we already have also a PR for the Jenks one.

I also see the conversation happening in the Jenks PR.

Jenks is tricky. Our backend implementation is buggy. I prefer to add STD for the public release and postpone the decision about Jenks (or any other better alternative) for future releases. Thoughts?

cc @makella @VictorVelarde @davidmanzanares

**Comment by VictorVelarde** [comment]
@rochoa That seems perfectly reasonable to me. In fact, I have been working today in Standard Deviation method, see my UPDATE at https://github.com/CartoDB/carto-vl/pull/909

**Comment by makella** [comment]
It seems reasonable to me too (I think!). I know that our Jenks implementation is buggy and that overall to fix it is not trivial.

At the same time, I am inclined to say that some sort of "optimal" classification would be useful especially for our public release. My biggest fear is that someone is like "why isn't it here" and then we have to do some quick turn around to get something like that in.

Again, I understand the implications of this, so don't want to push that opinion too hard, but also want to do my "due cartographer diligence" and put it out there. 😃 

I also think it is a "biiig win" that we have support for unclassed maps and that we have the new standard deviation method (awesome @VictorVelarde)!! So those, we can promote a lot!

There is also the case of methods for skewed data (heads/tails also needs some work on implementation), etc. and I'm sure once we know more about the methods that the Data Science team are using, the list could grow.

One thing we can do to be prepared with an answer for the prioritization of a method like Jenks is to [read one or two research papers like this one](http://www.personal.psu.edu/cab38/Brewer_Annals.pdf) that suggest a method like Jenks does not improve the comprehension of a choropleth map vs a method like Quantiles (which we already have).

Lots of words to say, I'm ok with putting off Jenks since we have so much new functionality to highlight -- and if armed with the right information, we have a good reason for revisiting at another time.

**Comment by rochoa** [comment]
> My biggest fear is that someone is like "why isn't it here" and then we have to do some quick turn around to get something like that in.

Which one are you thinking of?

> There is also the case of methods for skewed data (heads/tails also needs some work on implementation), etc. and I'm sure once we know more about the methods that the Data Science team are using, the list could grow.

That's the problem, the list could go ad-infinitum. But we could have a roadmap where we can list what we will include in future releases or is planned to happen.

**Comment by makella** [comment]
@rochoa 
for skewed data, the options I see are:
- fixing head/tails
- the methods that you hear most about are progression classifications like [geometric](http://wiki.gis.com/wiki/index.php/Geometric_Interval_Classification) and arithmetic

**Comment by VictorVelarde** [comment]
We have just merged 'Standard Deviation' classification. 

I think we can keep this issue as a global reference for classification discussions and create new specific ones in the future, so I'm moving this to our backlog

**Comment by rochoa** [comment]
Thanks for the update, @VictorVelarde.

In order to avoid confusion, I created an extra issue just for tracking the Standard Deviation PR https://github.com/CartoDB/carto-vl/issues/946 and moved this main issue to the clarify column.

**Comment by rochoa** [comment]
I just created a new issue for discussing Jenks, see https://github.com/CartoDB/carto-vl/issues/1034.

I'm closing this one as we already implemented the rest of the proposed methods.

In the future, we will discuss new potential methods, e.g., heads & tails
