### ISSUE TITLE
Obtain prop value from features

### ISSUE THREAD

**Issue by RominaMartin** [CartoDB/carto-vl#1143]
Hello. I'm currently obtaining some prop values in my `viz` with a variable which contains the set of props in the viewport. I define my viz like this:

```
const viz = new carto.Viz(`
    color: rgba(204, 204, 204, 0.6),
    strokeWidth: 2,
    strokeColor: rgba(255,255,255,0.6),
    @list: viewportFeatures(prop('cartodb_id'), prop('o_pu'), prop('o_a'), prop('s_t'), prop('y_s'))
`);
```

I would like to do the same and obtain these props (`cartodb_id`, `o_pu`...) and some others but instead of obtaining them for the current viewport for all results in the source.

I tried and add variables with it's value like this:
```
const viz = new carto.Viz(`
    color: rgba(204, 204, 204, 0.6),
    strokeWidth: 2,
    strokeColor: rgba(255,255,255,0.6),
    @o_pu: prop('o_pu'), 
    @o_a: prop('o_a')
     ...
`);
```

When I do it I get a `CartoValidationError: [Missing required property]: A property needs to be evaluated in a 'feature'.`

So I'm still not sure on how to accomplish this, thank you on any help you can provide and I'm sorry to bother if it's a simple question.

**Comment by VictorVelarde** [comment]
Hi, @RominaMartin 

We don't have a thing such as *globalFeatures*. The reason is that the number of features in a source is potentially so high, that it doesn't look efficient or even feasible. If your dataset is small enough, you could try with another strategies, outside CARTO VL.

The `CartoValidationError` you include indicates that "@o_pu" and "@o_a" properties are meant to be used within a feature (for example using `carto.Interactivity`, as in https://carto.com/developers/carto-vl/guides/add-interactivity-and-events/).

Just one more detail. You should use '$o_pu', '$o_a'... when including your columns using the String API, instead of prop('o_pu'). 

Compare the JavaScript API
```js
width: s.div(s.prop('population'), 10000)
```
vs the more compact String API:
```
width: $population / 10000 
```

**Comment by RominaMartin** [comment]
Oh okay got it, thank you!
