### ISSUE TITLE
Get cluster count info from metadata

### ISSUE THREAD

**Issue by elenatorro** [CartoDB/carto-vl#1287]
## Context

Related PR: https://github.com/CartoDB/carto-vl/pull/1281

When using `clusterCount()` expression, we rely on `_cdb_feature_count` property from the metadata. However, by default, this property does not contain the following information about the features:

- `avg`
- `min`
- `max`
- `sum`

![screenshot 2019-03-05 at 12 31 30](https://user-images.githubusercontent.com/3824953/53802737-e1c9c900-3f42-11e9-92f8-b7bfaad29d93.png)

In order to use `clusterCount()` with global aggregations, we'd need to know these values.

**Comment by jgoizueta** [comment]
I'm sorry to be the bearer of bad news but I'm afraid (as I've discussed with @elenatorro) that we can't do that (compute global aggregations of cluster count).

This is because cluster count stats vary with zoom level (clusters are large for small zoom levels and small for larger zooms), while the global stats in the metadata are computed once per map instantiantion, so they cannot be zoom-dependent.

To make this efficient we'd need to be able to request per-zoom cluster (i.e. aggregated) stats from the backend.

We can compute viewport aggregations of the cluster aggregations, though, by traversing the viewport features.

So what I'd do is document the fact that global aggregations cannot be applied to cluster aggregations (and perhaps provide an error or warning when done so, as @elenatorro has suggested), and tip the users to use viewport aggregations instead.

**Comment by elenatorro** [comment]
Thank you very much for the clarification @jgoizueta! It was very helpful. I'm going to link this information to the current PR and update it. Closing this issue.
