### ISSUE TITLE
Mobile maps are not able to load the data

### ISSUE THREAD

**Issue by cmongut** [CartoDB/carto-vl#1400]
These maps have been created with CARTOframes.

You can check the issue opening [this blog pos](https://carto.com/blog/visit-pattern-footfall-data-safegraph/)t with your mobile phone.

cc @CartoDB/rt-managers

**Comment by oriolbx** [comment]
cc @jesusbotella

**Comment by jesusbotella** [comment]
As far as I see, it throws this error on my iPhone X:
```
CartoRuntimeError: [WebGL] WebGL parameter 'gl.MAX_VERTEX_TEXTURE_IMAGE_UNITS' is below the requirement: 8 < 16
```

So I guess that my mobile phone (and many others, I guess) doesn't meet the needed requirements for CARTO-VL.

**Comment by cmongut** [comment]
😬 Do you think we can do something to solve it?

**Comment by Eh2406** [comment]
We hit this at work this week. It was something of a show stopper on a flagship product. It was recently introduced in 1.4.1. Luckily we use Carto-vl thure the js bindings, so we were able to revert to the 1.4.0 version. WItch works just fine for us.

**Comment by jdgodchaux** [comment]
Hi folks! Thanks for also reporting @Eh2406 ! I'm pasting a message from your team at SEMCOG Jacob, and hopefully that can provide @jesusbotella and others with some context for the problem:

> We did a bit of poking around, and determined that pinning our CARTO VL version to 1.4.0 makes our map load just fine on our iOS devices.  It looks like it was the 1.4.1 release that broke VL on iOS.  The CARTO VL compatibility tester map also runs smoothly when we open it in a JSFiddle and change the version to 1.4.0. 

> Jacob dug this out of the GitHub logs: https://github.com/CartoDB/carto-vl/pull/1387

> I can’t speak for other users of CARTO VL, but our map runs quite well on iOS devices with MAX_VERTEX_TEXTURE_IMAGE_UNITS == 8.  For now, we’re going to pin our map to 1.4.0 for next week’s presentation.

**Comment by jdgodchaux** [comment]
After reviewing https://github.com/CartoDB/support/issues/2119 it looks like @VictorVelarde decided on setting `MAX_VERTEX_TEXTURE_IMAGE_UNITS` to 16 after internal deliberation. It sounds like setting this value to 8 may allow CARTO VL maps to work on even very new iOS devices. I, of course, don't know the downside of setting `MAX_VERTEX_TEXTURE_IMAGE_UNITS` below 16, but if there's minimal impact elsewhere, I think that would be a welcome change. Thanks!

**Comment by VictorVelarde** [comment]
Hi,

First, regarding to mobile devices, we have to assume that CARTO VL has not a broad compatibility, due to its WebGL requirements. We've had some issues in the past (eg with some Huawei devices) , and we are currently not going to work on expanding that support.

Having said that, we decided to set that threshold to 16 having in our mind a desktop user (where most <= 5 years old computers are included), and that guarantees there's no problem there. But we can reconsider that value if it allows a significant amount of devices to be effectively included. 

So I propose to lower that threshold to 8, as you were suggesting, to run some tests and, if everything is ok, then to create a patch to the library. And @Eh2406 it would be very useful for us to validate with you the approach, so we might contact you soon about it.

**Comment by cmongut** [comment]
Agree @VictorVelarde 👍

**Comment by VictorVelarde** [comment]
If everything goes fine, we're gonna release a patch very soon, and that will be hopefully integrated in CF beta-4

**Comment by jdgodchaux** [comment]
:wave: @VictorVelarde, @jesusbotella When this change is complete, will this be incorporated into a new release of CARTO VL, or a hotfix in the current release?

**Comment by VictorVelarde** [comment]
hi @jdgodchaux,

On one hand, it will be a patch version in CARTO-VL. So a new v1.4.2 is going to be released. If the client is using JavaScript, they will have just to check they pick the updated the reference (from npm or cdn reference).

On the other hand, regarding to Kuviz visualizations in CARTOframes: I have checked an [example](https://cartodb.github.io/carto-vl-maps/blog/safegraph/safegraph-map-2.html), which was embedded in this [blog post](https://carto.com/blog/visit-pattern-footfall-data-safegraph/) and CARTO VL is being referenced using 'minor', pointing to **v1.4**. That means that it will get the fix for free, without requiring any change in the kuviz, nor a new CARTOframes version.

Just to be sure, we'll have to check that no reference exists in CARTOframes using CARTO VL 'patch' versions. (cc/ @Jesus89)

**Comment by jdgodchaux** [comment]
Awesome, thanks @VictorVelarde !!

**Comment by VictorVelarde** [comment]
Just for the record, the percent commented by @alejandraarri corresponds to the MAX_VERTEX_TEXTURE_IMAGE_UNITS parameter, which seems to affect to quite a few IOS devices. But the overall percent we support is indeed lower for mobile, as there are other limiting parameters besides that (specially the OES_texture_float extension one).

**Comment by andy-esch** [comment]
Hey all, I just tried to see if I could get the maps to display in my mobile browser (chrome, iphone se) and got this when I scrolled down to the map and it just started loading:
![IMG_88C107869C1C-1](https://user-images.githubusercontent.com/1041056/67690047-9ac99180-f972-11e9-8da1-24caab44ee06.jpeg)


I briefly saw the basemap, tabs for widgets/legend, and then got that.

**Comment by VictorVelarde** [comment]
@andy-esch is that the only CARTO VL viz you can't open?

Can you see for example https://carto.com/developers/carto-vl/examples/#example-check-for-browser-support ?

**Comment by andy-esch** [comment]
I went through the examples one by one. They worked until I got to "Add multiple source layers". I reloaded the page and tried loading that one again, which was successful. I kept going through trying new examples and they'd randomly work or not work. I don't see a pattern to the failures :/
