### ISSUE TITLE
Suggestions for technical blog posts

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/carto-vl#323]
This is for everyone @davidmanzanares @Jesus89 @IagoLast @makella @jgoizueta @rochoa 

The marketing team has asked us to write technical blog posts about VL that we could publish after Locations NY, to revitalize the announcement. 

I'm creating this issue just to dump blog posts ideas, assigned them and then create single issues for each one.

**Comment by makella** [comment]
Cartography ideas (will add more as they come to me):
- Multi-scale thematic cartography is here with CARTO VL
- Understanding VL's styling syntax
- How to make X map with CARTO VL

**Comment by IagoLast** [comment]
@makella as part of #335 I have planned to write a post about the VL´s syntax.

BTW cc @arianaescobar @rochoa we need to give this language a name ;)

**Comment by Jesus89** [comment]
Viz language?

**Comment by makella** [comment]
@IagoLast ok! all yours! I was thinking along the lines of how it resembles turbocarto and things like that. if you weren't planning on adding that, it would be a good idea since we've been teaching TC to our users and we thought a lot about that in the initial stages. Also, the intuitive nature of how you define styling, etc.

**Comment by rochoa** [comment]
Closing this issue. We already have some blog post planned and there are enough suggestions here.
