### ISSUE TITLE
Point color changes with the zoom

### ISSUE THREAD

**Issue by IagoLast** [CartoDB/carto-vl#348]
Example [here](https://cartodb.github.io/carto-vl/examples/editor/index.html#eyJhIjoiY3JvcF9sb3NzXzIwMTciLCJiIjoiIiwiYyI6ImNhcnRvZ2wiLCJkIjoiaHR0cHM6Ly97dXNlcn0uY2FydG8uY29tIiwiZSI6IndpZHRoOiAxMFxuY29sb3I6IHJhbXAobGluZWFyKCRhY3Jlc19sb3N0LCAwLCAxMDAwKSwgUFJJU00pXG5yZXNvbHV0aW9uOiAxIiwiZiI6eyJsbmciOi0xMTQuMzE5Nzg0OTg0Mzg4MSwibGF0Ijo0My44MDMyNjk3NDIxOTAwNTR9LCJnIjo0LjA5MzE4NTI1MTM4MDc2NCwiaCI6IkRhcmtNYXR0ZXIifQ==)
---

I have a map where the color of the points changes on zoom in/out
Maybe is a backend issue or is related with some aggregations but I think color must be consistent at all zoom levels 

[![https://gyazo.com/18a13dfbb146786f08856f3bea8822a7](https://i.gyazo.com/18a13dfbb146786f08856f3bea8822a7.gif)](https://gyazo.com/18a13dfbb146786f08856f3bea8822a7)

**Comment by davidmanzanares** [comment]
There are multiple points on the same positions: https://cartodb.github.io/carto-vl/examples/editor/index.html#eyJhIjoiY3JvcF9sb3NzXzIwMTciLCJiIjoiIiwiYyI6ImNhcnRvZ2wiLCJkIjoiaHR0cHM6Ly97dXNlcn0uY2FydG8uY29tIiwiZSI6IndpZHRoOiAxMFxuY29sb3I6IG9wYWNpdHkocmFtcChsaW5lYXIoJGFjcmVzX2xvc3QsIDAsIDEwMDApLCBQUklTTSksIDAuMilcbnJlc29sdXRpb246IDAuMSIsImYiOnsibG5nIjotOTAuOTcwMDA0MDA0ODYwNzUsImxhdCI6NDIuMjI1NTM3MDM4MzI3MTA0fSwiZyI6My45OTc2ODg4Nzg0Nzg0NTk0LCJoIjoiRGFya01hdHRlciJ9

If this is a problem, I think it will be a Maps API problem, but I wouldn't focus on this since this popping occurs (at least on this case) for a style that shouldn't be used in the first place since you are hiding many points behind other points, losing much information.

cc @jgoizueta

**Comment by makella** [comment]
@IagoLast 

In addition to the overlapping points that @davidmanzanares mentions (which basically are repeating county points for each kind of crop that was lost over a one year period) I think it has something to do with interpolating a category scheme with numeric data.

Not sure what attribute you are symbolizing on in the first screenshot, but if it is a numeric field (`$acres_lost`) you shouldn't use a category scheme. You are ramping linearly with a color scheme meant for categorical data.

I wonder if that is exacerbating what you are seeing especially with the comibination of opacity. Basically, the overlapping points are getting a mix of all of those colors so when you zoom in, and the values change so much for category colors, logically, it would make sense to me that you see changes.

For example, if you color the points based on the crop type, I don't see the same degree of change as I do with the linked example above:
https://cartodb.github.io/carto-vl/examples/editor/index.html#eyJhIjoiY3JvcF9sb3NzXzIwMTciLCJiIjoiIiwiYyI6ImNhcnRvZ2wiLCJkIjoiaHR0cHM6Ly97dXNlcn0uY2FydG8uY29tIiwiZSI6IndpZHRoOiAxMFxuY29sb3I6IG9wYWNpdHkgKHJhbXAoJGNvbW1vZGl0eV9uYW1lLHZpdmlkKSwwLjQpXG5yZXNvbHV0aW9uOiAwLjEiLCJmIjp7ImxuZyI6LTk3LjA0ODAzNDQ1MTY5NjAzLCJsYXQiOjQwLjgzOTA3MDgzMDc0MzM3fSwiZyI6NC42MjE0Mjg2OTU3OTg3MjMsImgiOiJEYXJrTWF0dGVyIn0=

And just to give some examples of how to symbolize these kinds of overlapping data with some cartography: 

if you want to display `$acres_lost` and show the variation between the overlapping points as well as the TYPE of crop (`$commodity_name`), you can do something like:
https://cartodb.github.io/carto-vl/examples/editor/index.html#eyJhIjoiY3JvcF9sb3NzXzIwMTciLCJiIjoiIiwiYyI6ImNhcnRvZ2wiLCJkIjoiaHR0cHM6Ly97dXNlcn0uY2FydG8uY29tIiwiZSI6IndpZHRoOiAkYWNyZXNfbG9zdC8xMDAwXG5jb2xvcjogb3BhY2l0eSAocmFtcCgkY29tbW9kaXR5X25hbWUsdml2aWQpLDAuNClcbnJlc29sdXRpb246IDAuMSIsImYiOnsibG5nIjotOTYuMzkxMDU0NTk4OTAzNjgsImxhdCI6NDAuODc5Nzg2NDcyNjg5MDM0fSwiZyI6NC4xNjQzNTYxNTA3MDU1NzQsImgiOiJEYXJrTWF0dGVyIn0=


Alternatively:
https://cartodb.github.io/carto-vl/examples/editor/index.html#eyJhIjoiY3JvcF9sb3NzXzIwMTciLCJiIjoiIiwiYyI6ImNhcnRvZ2wiLCJkIjoiaHR0cHM6Ly97dXNlcn0uY2FydG8uY29tIiwiZSI6IndpZHRoOiAkYWNyZXNfbG9zdC8xMDAwXG5jb2xvcjogb3BhY2l0eShyYW1wKGxpbmVhcigkYWNyZXNfbG9zdCwgMTAwLCAxMDAwMDApLCBpbnZlcnNlKGVtcmxkKSksIDAuNClcbnJlc29sdXRpb246IDAuMSIsImYiOnsibG5nIjotOTcuNzY3MDc4MjE0MjYyMTQsImxhdCI6NDEuOTM1Mjc1MTc2MzczNzV9LCJnIjozLjg2MTY2MzkxMjgyOTk3NDMsImgiOiJEYXJrTWF0dGVyIn0=

In both of those examples, since the data are symbolized in a "proper" way, you don't get that effect.

**Comment by davidmanzanares** [comment]
I think there was no issue in the first place here. Feel free to reopen with more details if that wasn't the case.
