### ISSUE TITLE
torque expression naming

### ISSUE THREAD

**Issue by rochoa** [CartoDB/carto-vl#524]
Let's discuss if this is the best name we can have for the expression itself, without considering the _Torque animated Maps in CARTO_ thing.

---
**note**: To be merged _after_ the release.

**Name options**:

* [x] simulation: consistency
* [x] sim (Simulation Iterative Matching): consistency, short name, descriptive
* [?] animation: we already have the "animate" expression. We would have to rename "animate" to "duration".
* [?] Rename "animate" to "transition" and "torque" to "animation"

**Comment by jgoizueta** [comment]
If we leave marketing issues aside I'd choose a name that describe the behaviour rather than torque, but that's not easy given this expression's weirdness factor. Here are the names that come to my mind, and I'm not perfectly happy with any of them:

* simulation (timeSimulation?)
* cycle (timeCycle?)
* clock
* animation

just my 2c

**Comment by pramsey** [comment]
From the chat: 

I’m sure many characters were spilled on this but using “torque” as the animation keyword just continues a prior bad decision (letting the library name leak into the user experience in editor). Call it “animation” or “animator”, please

As an addendum, keeping “torque” is an implicit statement that maintaining continuity for existing devs is more important then providing clarity for new devs. I’d posit that, as a company that still considers “growth” the alpha and omega, catering to new devs is probably the higher priority

**Comment by davidmanzanares** [comment]
Yes, we basically stuck to `torque` for a lack of a better name.

I don't like the `animation` or its variants because we already have an `animate` expression (although it is very basic), and I find `animation` too generic.

From @jgoizueta proposals, I like `simulation` or one variant of it like `simulate` or `sim`.

What do you think?

**Comment by elenatorro** [comment]
I like these options:

* transition
* simulation
* bounce (?)

`Simulation` is very consistent with the naming we are using now in the Torque class. I also like `transition` because the parameters sent to the function, in my opinion, describe what a transition does.

**Comment by IagoLast** [comment]
- temporalFilter

**Comment by ivanmalagon** [comment]
+1 to `transition`

I like also some variation on `temporalFilter` like `filterByTime`.

**Comment by arianaescobar** [comment]
@davidmanzanares Why do you think that `animation` is too generic?

**Comment by elenatorro** [comment]
I do not like `temporalFilter` or `filterByTime` because in my opinion I would like to keep expressions as simple as possible. I like `animation` too, but it sounds also generic because it is not *exactly* what it does.  I like both `animation` and `transition` because these words are also used in CSS, and they sound familiar to me. 

* [Transition CSS](https://developer.mozilla.org/en-US/docs/Web/CSS/transition)
* [Animation CSS](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Animations/Using_CSS_animations)

**Comment by jgoizueta** [comment]
I like `sim` (Simulation Iterative Matching). It's short and relates to `get/setSimTime`.

**Comment by elenatorro** [comment]
I like `sim` as a shortcut for `Simulation Iterative Matching`, we would have to add it in the documentation. In my opinion, is short but descriptive.

**Comment by arianaescobar** [comment]
I like how short `sim` is, although it's not too self-explanatory on its own and **Simulation** has the connotation of "imitating reality" and I'm not sure if we want to infuse our animation capabilities with that.

**Comment by IagoLast** [comment]
<img width="501" alt="screen shot 2018-06-22 at 12 37 15" src="https://user-images.githubusercontent.com/2657897/41772462-048cef42-7619-11e8-9065-f3c00fe32071.png">

I think we can move this forward
