### ISSUE TITLE
Interactivity makes the map slow

### ISSUE THREAD

**Issue by rubenmoya** [CartoDB/carto-vl#526]
@davidmanzanares told me to add this screenshot:

![screen shot 2018-06-07 at 14 36 05](https://user-images.githubusercontent.com/905225/41099954-4ded27a2-6a60-11e8-8c1c-13e8f59a6006.png)

**Comment by rochoa** [comment]
This also happens with the `featureClick` event. The performance degrades even when you are moving the pointer over the map.

**Comment by davidmanzanares** [comment]
Ok, We made a quick review of the source code and we found some interesting things:

- We are doing "point in polygon" every time an Interactivity object is created for a layer. Without checking that the user is listening for the move event.
- In `dataframe._getPolygonAtPosition` we are checking against all triangles without using their AABBs, nor indexes
- We already have the construction of AABB, since they are used to collision test the viewport to them for the viewport Agg functions. We just need to use them.
- We are doing the necessary per-feature `eval` **per triangle**
- Similar problems exists for lines

**Comment by davidmanzanares** [comment]
With @rubenmoya code I tested that https://github.com/CartoDB/carto-vl/pull/538 fixes it.

The PR addresses:
- "We are doing "point in polygon" every time an Interactivity object is created for a layer."
- "We are doing the necessary per-feature eval per triangle"
- "Similar problems exist for lines"

It doesn't address the lack of AABB and indexes. However, IMO this issue should be marked as fixed once that PR is merged since the performance is quite good already.

**Comment by davidmanzanares** [comment]
Fixed by https://github.com/CartoDB/carto-vl/pull/538
