### ISSUE TITLE
Review expressions guide

### ISSUE THREAD

**Issue by rochoa** [CartoDB/carto-vl#532]
After the initial feedback, we should review the expressions guide.

**Comment by arianaescobar** [comment]
I believe that the guide is good enough as an **introduction**, which is what we meant to do. Instead of changing that one, I would recommend creating a bit more advanced one focusing on value. 

Something like "How to use expressions" where we could teach: 

- How to mix different expressions on a single property (from a simple one to a very complex one)
  - How to nest those (a conversation that I strongly suggest us having) 
- Showing plenty of examples that showcase the value of each expression. For example:
  - Adjust a defined property to the viewport, or
  - Cluster data to improve performance 


my 2 cents 🙃

**Comment by makella** [comment]
Ok! Good points... thanks for reviewing @arianaescobar !

Regarding this,
>How to nest those (a conversation that I strongly suggest us having)

YES going to open an issue for discussion and if we can, let's bring it up with the crew at our Monday morning meeting.

**Comment by rochoa** [comment]
I just created an issue based on your comments.
