### ISSUE TITLE
Style by string values

### ISSUE THREAD

**Issue by ramiroaznar** [CartoDB/carto-vl#555]
Is it possible to style by string values? 

| cartodb_id | the_geom | color   |
|------------|----------|---------|
| 1          | Point    | red     |
| 2          | Point    | #fabada |

Like using something like this...

```
`
@color: $color
  color: @color
`
```

cc @makella @arianaescobar @elenatorro

**Comment by makella** [comment]
@ramiroaznar not at this time. That was something that came up during the hackathon... I did some testing and couldn't get it to work.

**Comment by ramiroaznar** [comment]
Good to know!

**Comment by ztephm** [comment]
[stringstyles.html.zip](https://github.com/CartoDB/carto-vl/files/2275833/stringstyles.html.zip)


FYI for troubleshooting I'm also not getting it to work trying these cases:

![screen shot 2018-08-09 at 4 28 14 pm](https://user-images.githubusercontent.com/1779444/43923991-58bf10b0-9bf1-11e8-957e-941be6f96dd8.png)

```javascript
    const viz = new carto.Viz(`
        @category_colors: [pink, red, darkRed]

        width: 100
        color: ramp(linear($popCount, 0, 200), @category_colors)
        strokeColor: blue
        strokeWidth: 1
    `);
```

![screen shot 2018-08-09 at 4 24 45 pm](https://user-images.githubusercontent.com/1779444/43923827-d56c5f4c-9bf0-11e8-8a9f-7e8692674188.png)

```javascript
    const viz = new carto.Viz(`
        @category_colors: ['pink', 'red', 'darkRed']

        width: 100
        color: ramp(linear($popCount, 0, 200), @category_colors)
        strokeColor: blue
        strokeWidth: 1
    `);
```

![screen shot 2018-08-09 at 4 35 43 pm](https://user-images.githubusercontent.com/1779444/43924322-547a83a8-9bf2-11e8-810b-43e7b8f1f7a1.png)

**Comment by elenatorro** [comment]
I have opened a new issue with @ztephm's bug.

**Comment by davidmanzanares** [comment]
I think it's better to leave this as a `won't fix` since it's a little bit hacky to store color information in a column. It's always better to style within CARTO VL by the original feature property.

**Comment by arianaescobar** [comment]
🙄

**Comment by ramiroaznar** [comment]
@davidmanzanares why? cc @makella

**Comment by davidmanzanares** [comment]
I think it's hacky because the style shouldn't be mixed with the real data, this is from my point of view like mixing HTML, JS, and CSS all in one place. It's better to have separation of concerns.

This trick also imposes limits. For example, if a user has a color property computed based on a `price` property and then he wants to get the average (or other aggregation) of the `price` the tiles will need to contain both the color and the price, bloating tile size unnecessarily. Other limitation would be that Maps API clustering aggregation wouldn't work well anymore.

I try to think of good reasons for doing this and I only have come up with these:
 - Privacy purposes. With vector tiles is easy to retrieve the original dataset with only access to the tiles (map). This case is a legitimate use case, but if that privacy is that important you probably shouldn't use CARTO VL in the first place.
- Avoid styling with CARTO VL. Since CARTO VL styling performance is GPU accelerated performance is not going to be improved by styling before CARTO VL. The other reason would be to overcome a CARTO VL styling limitation (for example wanting a classification method that is not supported within CARTO VL). I think this is a legitimate issue, but I think that those precomputations are useful in numeric-to-numeric way not in a numeric-to-color way because once the input is transformed to some intermediate numeric value CARTO VL can transform that to colors.
