### ISSUE TITLE
Examples for beta release

### ISSUE THREAD

**Issue by rochoa** [CartoDB/carto-vl#63]
TBD with @inigomedina.

**Comment by makella** [comment]
@davidmanzanares @rochoa after going back and forth, back and forth, I started a different style today to document some basic examples.

I will meet with Cillas tomorrow to discuss further details.

I'm still not done (because I couldn't decide what to do) and what I am putting together needs work still, but at a basic level, you can see some example maps (just screenshots for now), basic description, and associated styling. Will continue chipping away at this the remainder of the week to make it more robust and cover all the "basics"

https://github.com/CartoDB/renderer-prototype/wiki/Map-Examples

**Comment by makella** [comment]
@rochoa @davidmanzanares 

I think I've gotten through the point map types...

Right now, the biggest things we are missing are additional classification methods and classed bubble maps for points

I put some resources together please have a look. 

_As a side note, these are by no means "final docs" and as you will notice are still incomplete in some areas_

+ [Styling and Operator Tables](https://github.com/CartoDB/renderer-prototype/wiki/Styling-and-Operator-Tables)
+ [Styling Points](https://github.com/CartoDB/renderer-prototype/wiki/Styling-Points)

**Comment by arianaescobar** [comment]
@makella and I were talking about the examples yesterday, trying to make sense about what extra work we might need for the beta release and I just created [this document](https://docs.google.com/spreadsheets/d/1hpoA1ysvU-5JZt6lLNnstetQ0GlkhHSOZR55N6n5DNc/edit?usp=sharing) that will help us to quickly visualize what's needed.

**Comment by makella** [comment]
❤️ this!

**Comment by arianaescobar** [comment]
To discuss: for the examples, should we use javascript or the string API?

**Comment by makella** [comment]
We have been using string, so it was easier for me to modify, I'd say let's stick with that! @Jesus89 cool with you?

**Comment by arianaescobar** [comment]
Yeah, Jesus and I agree on using string, but there are a few using javascript. We should change those then.

**Comment by arianaescobar** [comment]
To-do: 

- [ ] Add spinner to examples

**Comment by makella** [comment]
👍
