### ISSUE TITLE
Keep a Changelog

### ISSUE THREAD

**Issue by IagoLast** [CartoDB/carto-vl#642]
I see 3 possible approaches here:

### Manual Changelog

On every version bump/release manually update the changelog (something like the news.md file in builder)

### Automated Changelog
Some tools like [conventional changelog](https://github.com/conventional-changelog/conventional-changelog) allow to create a [well formated changelog](https://keepachangelog.com/en/1.0.0/)  with a command, the bad part if we had to use some commit standard for example: https://conventionalcommits.org/

### Devlog
We had [a similar issue with CARTO.js](https://github.com/CartoDB/carto.js/issues/2011) and we created a tool to generate a changelog without changing our commit rules, just using a quick code in the github merges

you know the pros & cons of each one so feel free to share your point of view @davidmanzanares @elenatorro @jgoizueta @Jesus89 @rochoa

**Comment by davidmanzanares** [comment]
I propose to use the guidelines shown here: https://keepachangelog.com/en/1.0.0/

From my point of view, we should update the changelog in each PR manually. I don't like the idea of automatizing it because usually there are many commits for just one feature, while there is one PR for each feature.

I think that we should enforce this convention by checking at code-review time that the changelog is updated.

**Comment by rochoa** [comment]
What if we could automate it based on the contents of the PR description?

**Comment by Jesus89** [comment]
I'm not very fan of automation in this case, because IMO there is always a particular case that can not be covered with automation and external APIs. For example, a feature closed in two PRs or a dev-happiness PR you don't want to include in the changelog.

I think we can update manually the changelog in each PR, if required, as we did in Builder, but following the `keepachangelog` format: Added, Changed, Fixed, Removed (Deprecated, Security).

**Comment by rochoa** [comment]
Fair enough. If you are happy doing manually, I'm also happy. 😃We have been doing that in Engine API projects for years.

**Comment by davidmanzanares** [comment]
Manual then :rocket:

**Comment by davidmanzanares** [comment]
Do we agree on starting it after the next release?

I don't say to start it now because we would need to look back for previous changes to make the version complete.

**Comment by Jesus89** [comment]
We have the changelog info for v0.6.0 version so I think we could add the information and continue after that.

Maybe for the public release, we should do a summary for the previous versions.

**Comment by Jesus89** [comment]
I have added a branch with the changes from 0.6.0 (0.6.2 and unreleased) https://github.com/CartoDB/carto-vl/pull/814.

Please add anything that you miss since 0.6.0 in the file. And remember to follow always the principles https://keepachangelog.com/en/1.0.0/#how :scroll:

**Comment by davidmanzanares** [comment]
:+1:

**Comment by Jesus89** [comment]
Closed by https://github.com/CartoDB/carto-vl/pull/814
