### ISSUE TITLE
Accessing variable when it changes from one property to other with NaN value

### ISSUE THREAD

**Issue by rochoa** [CartoDB/carto-vl#706]
When blending from:

```
@Val: $colwithvalidnumber
strokeWidth: 0.8
color: blend(grey, ramp(linear($colwithvalidnumber, 0, 1000), temps), isnan($colwithvalidnumber))
```

To:

```
@Val: $colwithNaN
strokeWidth: 0.8
color: blend(grey, ramp(linear($colwithNaN, 0, 1000), temps), isnan($colwithNaN))
```

And accessing the variable in the interactivity.

See https://github.com/CartoDB/carto-vl/compare/replacer-bug.

**Comment by elenatorro** [comment]
Question: how it could be possible to have NaN values in a property?

**Comment by davidmanzanares** [comment]
A `NaN` value is put when a property is `NULL` within Maps API, or undefined (with MVT API) or simply, `NaN`

**Comment by elenatorro** [comment]
After several tests, I think there is no bug here. This is what I have tested (using the code above):

* Interactivity
```js
    const interactivity = new carto.Interactivity(layer);
    
    interactivity.on('featureEnter', event => {
      if (event.features.length > 0) {
        event.features.forEach((feature) => {
          console.log('feature', feature.variables.val.value);
        });
      }
    });
```

1. Accessing the variable without `blendToViz` where all the values in the column are a valid number:
All values are the respective value in the column.

2. Accessing the variable without `blendToViz` where all the values in the column are `null` :
All values are `NaN`.

3. Accessing the variable with `blendToViz` from a column where all the values are a valid number to a column where all the values in the column are `null` :
All values are `NaN`.

4. Accessing the variable with `blendToViz` from a column where all the values are null to a column where all the values in the column are valid numbers:
All values are the respective value in the column.

I think we should close this issue if we do not know what the actual problem is cc @davidmanzanares @Jesus89

**Comment by davidmanzanares** [comment]
:+1:
I'll try to take a little look at it to be sure, but this is an old problem, it could have been fixed accidentally.

**Comment by rochoa** [comment]
I haven't been able to reproduce the original issue. What, IIRC, it was about not transitioning from a NaN value to a valid number.

However, I've found another issue regarding `blendTo` and variables, gonna create a new issue.
