### ISSUE TITLE
Interactivy stops working when 'prop' filter is applied

### ISSUE THREAD

**Issue by Josmorsot** [CartoDB/carto-vl#728]
Hi,

I've just found a bug using filters. Given a layer with an 'Interactivity' assigned, when a filter is applied to this layer using any property, 'interactivity' is never launched again.

I've noted that this happens when using filters like 'in' or 'eq', but not using 'nin' or 'neq'.

I've just uploaded an example using the latest CARTO VL to this [branch](https://github.com/Josmorsot/featureClickCartoVL/tree/ivan/tooltip-not-working-after-filters)

In the example 'interactivity' should work until 'Turn off the some lines' is clicked.

Thanks!

**Comment by davidmanzanares** [comment]
Hi,

Sorry for the delay, feel free to ping me in the future with a "@davidmanzanares" to raise awareness.

This seems like a serious bug, I'll take a look ASAP.

Thank you!

**Comment by davidmanzanares** [comment]
Hello again, 

I was able to reproduce the issue with your provided `carto-vl.js` file, but I couldn't with the current `master` branch.

I think the root cause is the same as the one behind https://github.com/CartoDB/carto-vl/issues/676 and the fix for that already fixed this too.

Could you recheck with `master`?

**Comment by davidmanzanares** [comment]
This should fix the problem: https://github.com/CartoDB/carto-vl/pull/736

**Comment by Josmorsot** [comment]
Thank's @davidmanzanares!, I've just updated to that branch and now it's working fine.
