### ISSUE TITLE
Overzooming for SQL source

### ISSUE THREAD

**Issue by Josmorsot** [CartoDB/carto-vl#767]
Hi @davidmanzanares,

We're working on resolving the performance issues we currently have in Traffico. For this we've decided to do two things:

* Unify all layers.

* Apply 'viewportZoomToSourceZoom'. However, we're using 'carto.source.SQL' and this property does not exist for this data source object.

Do you think it would be possible to implement it?

Thanks!
Iván

**Comment by davidmanzanares** [comment]
Hi, I don't think we want to expose such a low level detail in the Maps API source. However, we would like to make the necessary changes to enable the use case. Could you give us much more context about it?

**Comment by Josmorsot** [comment]
Hi @davidmanzanares,

We've just finished the integration of CARTO VL in Traffico.
We first unified all layers into three (polygons, lines and points) but the performance didn't improve as much as we expected, so we decided to refactor
our layers and use 'carto.source.MVT' instead of 'carto.source.SQL' in order to be able to use 'viewportZoomToSourceZoom'.

Now, we are requesting tiles only for zoom levels 0, 4, 8,... Since this has resulted in a dramatic improvement in performance, we think it would be great to implement 'overzooming' in others source types or even do it automatically in Maps API.

Thanks!

**Comment by davidmanzanares** [comment]
Hi @Josmorsot,

Thank you for your feedback.

We are aware of the performance implications of using `viewportZoomToSourceZoom` and we are already working on giving good out of the box support in Maps API sources.

However, I cannot recommend the usage of `viewportZoomToSourceZoom`  with an MVT source and a Maps API backend. There are multiple reasons:
- Currently, Maps API returns over-simplified geometry in the sense that tiles will have their vertices simplified to a grid of 256x256 pixels, even though their resolution will be in a grid of 4096x4096.
- You won't be able to gain future Maps API only features and optimizations without changing the code
- The cost of future development will be higher without the Maps API abstraction (metadata and aggregations are handled easily with native Maps API sources).

I'm also curious about the current performance problems since there may be potential low-effort high-value optimizations, but this can only be seen by profiling the real application. Ideally, we would have access to it or to a Chrome profile JSON file.

**Comment by davidmanzanares** [comment]
As discussed off-channel, we've seen that the unified layer approach performance is quite good. Although we've seen that the application level function `groupBy` is responsible for a lot of CPU cycles. I think that its usage is a result of the unified approach. However, I think that it could be replaced by the usage of the native `viewportHistogram` (https://github.com/CartoDB/carto-vl/blob/master/src/renderer/viz/expressions/aggregation/viewport/ViewportHistogram.js#L25)

We are going to investigate the root of the problems in the pre-layer-unification version.

**Comment by rochoa** [comment]
Sorry, this slipped through the cracks.

I just want to reinforce what @davidmanzanares pointed before. Exposing `viewportZoomToSourceZoom` would be the cheap and quick route, however, it will be also the dirty one because that will prevent us for future optimizations, like https://github.com/CartoDB/carto-vl/issues/17.

Furthermore, it seems like there were other factors affecting the performance of your specific use-case. And, in the worst-case scenario, you can always interact directly with the Maps API and use a `source.MVT` source as a way to enable `viewportZoomToSourceZoom`. I highly discourage that, tho.

We won't enable this feature for the time being.
