### ISSUE TITLE
`Non-white` example is broken

### ISSUE THREAD

**Issue by Jesus89** [CartoDB/carto-vl#879]
https://cartodb.github.io/carto-vl/examples/editor/index.html#eyJhIjoidGFibGVfNXlyX2NvdW50eV9hY3NfY29weV8xIiwiYiI6IiIsImMiOiJtYW1hdGFha2VsbGEiLCJkIjoiaHR0cHM6Ly97dXNlcn0uY2FydG8uY29tIiwiZSI6IndpZHRoOiAoJGFzaWFuX3BvcCskYmxhY2tfcG9wKyRoaXNwYW5pY19vKS8kd2hpdGVfcG9wXG5jb2xvcjogaHN2YSgwLjUsIDEsIDEsIDAuNylcbnN0cm9rZVdpZHRoOiAwIiwiZiI6eyJsbmciOi05MC42OTkwNTg1MTI0MTE5NywibGF0Ijo0MC42MjE0NzUyMzQ0MTY2NjR9LCJnIjoyLjQ1NzMzNjA2NDIyMzUzMSwiaCI6IkRhcmtNYXR0ZXIiLCJpIjoiZGF0YXNldCJ9

![selection_260](https://user-images.githubusercontent.com/2227572/44459356-a6e8ef00-a609-11e8-9004-ac0835b5a27e.png)

We need to check if the example is broken or if there is a bug with the points size.

**Comment by makella** [comment]
woah!! i'm not sure exactly what is happening. i tried reducing the symbol sizes significantly and the point for Puerto Rico does not get smaller:

https://cartodb.github.io/carto-vl/examples/editor/index.html#eyJhIjoidGFibGVfNXlyX2NvdW50eV9hY3NfY29weV8xIiwiYiI6IiIsImMiOiJtYW1hdGFha2VsbGEiLCJkIjoiaHR0cHM6Ly97dXNlcn0uY2FydG8uY29tIiwiZSI6IndpZHRoOiBzcXJ0KCgkYXNpYW5fcG9wKyRibGFja19wb3ArJGhpc3BhbmljX28pLyR3aGl0ZV9wb3ApLzEwMDAwMDAwXG5jb2xvcjogaHN2YSgwLjUsIDEsIDEsIDAuNylcbnN0cm9rZVdpZHRoOiAwIiwiZiI6eyJsbmciOi05Mi4xNzEwODE2MjQ0NDg5NiwibGF0IjotMTIuNzY3NzQxMzc1Njg2NzI1fSwiZyI6Mi4zMTkxMDI0NTcxODY2MzM0LCJoIjoiRGFya01hdHRlciIsImkiOiJkYXRhc2V0In0=

You'll also notice that if you change the number i'm dividing by, that the map refreshes (or seems like it wants to) but keeps that size consistent.

cc'ing @davidmanzanares as we were seeing some super large sizes in Jeff's map, but as pointed out in the issue could have been related to suspicious application code.
https://github.com/CartoDB/carto-vl/issues/798#issuecomment-411444568

**Comment by davidmanzanares** [comment]
The issue is that in Puerto Rico there are values with `white_pop` equal to `0`, making the division by `white_pop` equal to Infinity, making the points super large (1024 px).

You can see these problematic outliers here: https://cartodb.github.io/carto-vl/examples/editor/index.html#eyJhIjoidGFibGVfNXlyX2NvdW50eV9hY3NfY29weV8xIiwiYiI6IiIsImMiOiJtYW1hdGFha2VsbGEiLCJkIjoiaHR0cHM6Ly97dXNlcn0uY2FydG8uY29tIiwiZSI6IndpZHRoOiByYW1wKCR3aGl0ZV9wb3A9PTAsIFsyLCAzMF0pXG5jb2xvcjogcmFtcCgkd2hpdGVfcG9wPT0wLCBbZ3JheSwgcmVkXSlcbnN0cm9rZVdpZHRoOiAwIiwiZiI6eyJsbmciOi04Mi4zOTcxMDI3NjI5MjY0MSwibGF0IjozNC4wOTk4MTUyNzU1MzUzNn0sImciOjMuOTM4NDI3ODE4NTMyNDA4NCwiaCI6IkRhcmtNYXR0ZXIiLCJpIjoiZGF0YXNldCJ9

Dividing by the total population seems to fix the issue, but of course, it changes the map: `https://cartodb.github.io/carto-vl/examples/editor/index.html#eyJhIjoidGFibGVfNXlyX2NvdW50eV9hY3NfY29weV8xIiwiYiI6IiIsImMiOiJtYW1hdGFha2VsbGEiLCJkIjoiaHR0cHM6Ly97dXNlcn0uY2FydG8uY29tIiwiZSI6IndpZHRoOiBzcXJ0KCgkYXNpYW5fcG9wKyRibGFja19wb3ArJGhpc3BhbmljX28pLyR0b3RhbF9wb3ApKjVcbmNvbG9yOiBoc3ZhKDAuNSwgMSwgMSwgMC43KVxuc3Ryb2tlV2lkdGg6IDAgIiwiZiI6eyJsbmciOi03OC4wNDQwMjczNzgwODE0NywibGF0IjozOS4xNDcyNDY1NjM2NTk0Mn0sImciOjMuMTMzNzIyNDMzNzI0Njk0LCJoIjoiRGFya01hdHRlciIsImkiOiJkYXRhc2V0In0=`

**Comment by makella** [comment]
interesting... ok so in our previous version of the map since we had a much smaller max width, we didn't get this artifact. 

@Jesus89
I filtered to `white_pop > 1` if we want to replace, we can add that parameter:
https://cartodb.github.io/carto-vl/examples/editor/index.html#eyJhIjoidGFibGVfNXlyX2NvdW50eV9hY3NfY29weV8xIiwiYiI6IiIsImMiOiJtYW1hdGFha2VsbGEiLCJkIjoiaHR0cHM6Ly97dXNlcn0uY2FydG8uY29tIiwiZSI6IndpZHRoOiBzcXJ0KCgkYXNpYW5fcG9wKyRibGFja19wb3ArJGhpc3BhbmljX28pLyR3aGl0ZV9wb3ApKjJcbmNvbG9yOiBoc3ZhKDAuNSwgMSwgMSwgMC43KVxuc3Ryb2tlV2lkdGg6IDBcbmZpbHRlcjogJHdoaXRlX3BvcCA+IDEgIiwiZiI6eyJsbmciOi04OS44MjAyMzQxODU0NDk4LCJsYXQiOjM4LjAyMDA5MTA5MTA1NzM0fSwiZyI6My4xMzM3MjI0MzM3MjQ2OTQsImgiOiJEYXJrTWF0dGVyIiwiaSI6ImRhdGFzZXQifQ==

@Jesus89

**Comment by Jesus89** [comment]
Double cc :joy: 

@makella do you want me to update the example with the new code?

**Comment by makella** [comment]
HAHAAA!!! i _really_ wanted you to know about this :)

sure! that would be great
