### ISSUE TITLE
Bug rendering opacity on zoom in

### ISSUE THREAD

**Issue by Jesus89** [CartoDB/carto-vl#90]
A feature with opacity < 1 is rendered correctly when the zoom is out. But when I zoom in the feature is rendered with opacity = 1.

![bug-render-point](https://user-images.githubusercontent.com/2227572/36420567-c84ec318-1635-11e8-87a0-735a9b513771.gif)

**Comment by davidmanzanares** [comment]
How can this be reproduced?

**Comment by Jesus89** [comment]
Try [this example](https://cartodb.github.io/renderer-prototype/example/mapbox.html#eyJhIjoicG9pbnQiLCJiIjoiIiwiYyI6ImFycm95by1jYXJ0byIsImQiOiJodHRwczovL3t1c2VyfS5jYXJ0by5jb20iLCJlIjoid2lkdGg6IDIwMFxuY29sb3I6IHJnYmEoMCwxLDAsMC41KSIsImYiOnsibG5nIjotNi44OTU5MjY3NzI4ODM4NTQsImxhdCI6MjQuODAzMDU4MDY4NTQ3MTczfSwiZyI6MS42NTk5NjEzMzUyMjg3MTE3fQ==).

**Comment by davidmanzanares** [comment]
Related to https://github.com/CartoDB/renderer-prototype/issues/91

This is probably not a rendering problem, if you go to the example you've provided you can see that the number of features increae to two, therefore, the opacity doesn't change, two identical points are renderered. This is probably due to Maps API returning two points.
