### ISSUE TITLE
Missing points on latitude 0

### ISSUE THREAD

**Issue by skgsergio** [CartoDB/carto-vl#922]
### Issue Description

I created a dataset that contains some points with latitude `0` and longitude `[-150, -120, -90, -60, -30, 0, 30, 60, 90, 120, 150]`. Then I tried to render it with CARTO VL and they are missing.

If you make the window small and use the minimun zoom possible the points get rendered (@jgoizueta told me to try this and its probably working because is the tile `0/0/0`).

### Example/Dataset
Dataset: https://team.carto.com/tables/testanim_static_points/public

Example using the editor: https://cartodb.github.io/carto-vl/examples/editor/index.html#eyJhIjoidGVzdGFuaW1fc3RhdGljX3BvaW50cyIsImIiOiIiLCJjIjoic2NvbmRlLWNhcnRvIiwiZCI6Imh0dHBzOi8ve3VzZXJ9LmNhcnRvLmNvbSIsImUiOiJ3aWR0aDogNVxuY29sb3I6IHJnYigyNTUsIDAsIDApIiwiZiI6eyJsbmciOjQzLjYxMzY3OTI5MDg2ODczLCJsYXQiOjEyLjYxNzg0NTE0MDE0MTA0M30sImciOjAsImgiOiJEYXJrTWF0dGVyIiwiaSI6ImRhdGFzZXQifQ==

/cc @jgoizueta @davidmanzanares

**Comment by jgoizueta** [comment]
* This happens only with tiled sources.
* This doesn't happen if the Y coordinates are slightly different from 0 (e.g. 1E-1)
* This doesn't happen if we change the `buffersize` to 2 (we're using the value 1).

**Comment by jgoizueta** [comment]
So the fact that changing the buffersize solves this seems to indicate it is a backend problem. Actually we used to have this problem, due to inaccuracies both in the Y=0 when transformed to webmercator and in the bbox used by Mapnik. But this was solved when we introduced `buffersize=1`, because the buffersize is larger than the numeric inaccuracies.

So this really puzzles me, since there seem to be no recent changes in the production stack (Mapnik, ...) /cc @Algunenano

**Comment by Algunenano** [comment]
I'm testing some changes in MVT but only in one production server and they shouldn't affect points. 

OTOH if you check the request at zoom level 1, 2 of the tiles are empty and 2 are not:
![image](https://user-images.githubusercontent.com/664253/45046032-37491a00-b075-11e8-92b5-23d1289725b0.png)

One of the tiles has 
```sql
[
  {
    "version": 2,
    "name": "layer0",
    "extent": 4096,
    "features": [
      {
        "type": 1,
        "id": 1,
        "properties": {
          "_cdb_feature_count": 1,
          "cartodb_id": 1
        },
        "geometry": [
          9,
          1364,
          0
        ]
      },
      {
        "type": 1,
        "id": 2,
        "properties": {
          "_cdb_feature_count": 1,
          "cartodb_id": 2
        },
        "geometry": [
          9,
          2730,
          0
        ]
      },
      {
        "type": 1,
        "id": 3,
        "properties": {
          "_cdb_feature_count": 1,
          "cartodb_id": 3
        },
        "geometry": [
          9,
          4096,
          0
        ]
      },
      {
        "type": 1,
        "id": 4,
        "properties": {
          "_cdb_feature_count": 1,
          "cartodb_id": 4
        },
        "geometry": [
          9,
          5460,
          0
        ]
      },
      {
        "type": 1,
        "id": 5,
        "properties": {
          "_cdb_feature_count": 1,
          "cartodb_id": 5
        },
        "geometry": [
          9,
          6826,
          0
        ]
      }
    ]
  }
]
```

The other:
```
[
  {
    "version": 2,
    "name": "layer0",
    "extent": 4096,
    "features": [
      {
        "type": 1,
        "id": 1,
        "properties": {
          "_cdb_feature_count": 1,
          "cartodb_id": 6
        },
        "geometry": [
          9,
          0,
          0
        ]
      },
      {
        "type": 1,
        "id": 2,
        "properties": {
          "_cdb_feature_count": 1,
          "cartodb_id": 7
        },
        "geometry": [
          9,
          1366,
          0
        ]
      },
      {
        "type": 1,
        "id": 3,
        "properties": {
          "_cdb_feature_count": 1,
          "cartodb_id": 8
        },
        "geometry": [
          9,
          2732,
          0
        ]
      },
      {
        "type": 1,
        "id": 4,
        "properties": {
          "_cdb_feature_count": 1,
          "cartodb_id": 9
        },
        "geometry": [
          9,
          4096,
          0
        ]
      },
      {
        "type": 1,
        "id": 5,
        "properties": {
          "_cdb_feature_count": 1,
          "cartodb_id": 10
        },
        "geometry": [
          9,
          5462,
          0
        ]
      },
      {
        "type": 1,
        "id": 6,
        "properties": {
          "_cdb_feature_count": 1,
          "cartodb_id": 11
        },
        "geometry": [
          9,
          6828,
          0
        ]
      }
    ]
  }
]
```

Aren't those the expected values? Or do you expect the tile at 0,0 (cartodb_id = 6) to be in all 4 tiles?

BTW, with those tiles I don't see anything in the editor.

**Comment by Algunenano** [comment]
> So, with buffersize=1, the points should be included in the tile whenever tilesize/256 > 7E-10
i.e. for tilesize > 1.8E-7 m, and this should be true for all practical zoom levels (e.g. even for z=32 tilesize is 0.0093 m)

Yes. The intersection (&&) with the bbox should discard anything beyond that. As you probably know there is plenty of conversions from Windshaft-cartodb -> Mapnik with those numbers so precision might not be great. Also, you added a bunch of scary extra conditions and aproximations in aggregation queries that I've never gotten around reviewing in detail. Does this also happen if you disable aggregation?

By the way, I'm unable to access Sergio's dataset and it would help a lot to have a concrete example:
- Point in `4326`or `3857`. `3857` is preferable so we avoid St_Transform roundings.
- Mapconfig with all settings (buffersize, aggregation, etc)
- Exact tile (z,x,y) where you this point is expected to show and isn't or viceversa.

With that, I could check the full query and see what's going on. And, more importantly, I could check also with St_AsMVT which doesn't have any intermediate rounding and I expect to be more precise (and maybe render the aggregation approximations unnecessary).

**Comment by jgoizueta** [comment]
You nailed the problem! I checked without aggregations and bang!
Thanks for the tip @Algunenano !! (I should have thought first of all in my own aggregations haha)

**Comment by jgoizueta** [comment]
So I've found the culprit, and I was, surprise, surprise... me.

Namely, we recently modify the tiler aggregations to avoid producing partially aggregated clusters (i.e. not fully within the buffer). This case is at the limit, with `resolution=1` and `buffersize=1`, the cells containing the points *should* be just included in the size, but it seems we're excluding them. With `resolution` < 1 this is fixed for the equatorial points. Using `placement='point-grid'` also fixes the problem, so we have some inconsistency in the aggregation queries. And `placement='sample'` produces an error "the geom  does not exist", so we've found also a bug in the tiler.

I'll open a ticket in the tiler, where this should be fixed.

**Comment by jgoizueta** [comment]
@skgsergio as a workaround, for the time being I would set the `resolution` in the visualization to something smaller than 1, e.g. 0.5.

**Comment by jgoizueta** [comment]
Actually, in cases like this, where aggregation is not really en effect, I think we should have a way to avoiding them completely (by having CARTO VL set  `aggregation: false` in the Mapconfig).

We could add a property in the viz to disable aggregations, or perhaps set resolution to 0 to disable it.

**Comment by jgoizueta** [comment]
For the record, what was happening was this: (which shouldn't be happening because the buffer actually contains the point, but aggregations are messing things in the backend)

For buffersize=2, the equator points, which due to PROJ transformation accuracy are moved slightly south, are both in the N and S neighbouring tiles. Then in the MVT they are snapped to the limit coordinates of 4096 (in the N MVT) and 0 (in the S MVT). We map this to -1 (N) and +1 (S) exactly and then for each tile we filter -1 <= Y < +1, so the points in the S dataframe are discarded. So we rely on the points being present in the N tile, (where it is not strictly due the the inaccuracies), and if it is only in the S tiles, we miss it.

![eqpoints](https://user-images.githubusercontent.com/5909/45152994-de8f9380-b1d2-11e8-9958-e8e2fcbdc5f3.png)

**Comment by jgoizueta** [comment]
I meant to expose in the public API. You're right this case is a bug (and can be handled with the resolution workaround).
But, if you (the user) know you won't be using aggregations, you have a small dataset and want to be sure each individual point is always present, it could be handy to disable aggregation (and more efficient on the backend, but probably that's not very relevant for the small datasets).

**Comment by jgoizueta** [comment]
I've looked at this in some depth, and while I was confused for some time because of different configurations in my local environments for Postgresql 9.6 and 10.1, I'm quite confident everything is under control now. 🤞 

All the problems found here should be solved by a couple of fixes in the tiler, described here:
* https://github.com/CartoDB/Windshaft-cartodb/issues/1034
* https://github.com/CartoDB/Windshaft-cartodb/issues/1033

Now, for future reference I'll write down some details here.

To understand what was happening we must be aware of the following facts about how the tiler aggregates the data.

- A) The tile buffer, defined by `buffersize` is adjusted (shrinking it if necessary) to exact aggregation grid limits, to avoid aggregation partial cells.
- B) The aggregated coordinates are then subject to round off and adjusted to MVT coordinates, which are integers with the range given by the MVT extent (currently we use 0 to 4096 coordinates).
- C) With versions of the PROJ library prior to 5, which we use currently in PostGIS, the points with latitude 0 end up having a tiny negative Y value (about 1E-10) in Web-Mercator.
- D) When generating tiles with Mapnik, it substitutes a value for `bbox` (the tile+buffer extents) in the SQL query, and that value is sadly less precise than the available numeric accuracy would allow.
- E) CARTO VL filters out tile points to avoid duplicates excluding points in the North and East tile boundaries, i.e. it filters with `-1 <= X,Y < +1` where -1, +1 are internal coordinates mapped to the MVT extent limit coordinates (0, 4096).

So, what was happening here?

The problem was that when adjusting the buffer to include only whole grid cells (A), we were losing the buffer; the buffer was exactly the size of the grid cell, but due to bbox inaccuracy (D) it missed the cell boundaries and got shrink down to the tile without a buffer.

Then, we have a case of naked tiles without buffer: In that case the Maps API guarantees that each aggregated point will be only in one single tile.

Our equator points, due to (C) are actually only in the tiles south of the equator, not in the northern ones (because we have a small negative Y).

But the tiny Y coordinates of our points get rounded to 0 in the MVT (Y=0 is the North border of the tile 
in MVT coordinates; note that the MVT Y coordinates increase from North to South).

So, not being inside the tile anymore, but on its North boundary, they are filtered out by (E). (Y < +1:  WRONG)

With smaller resolution, cells are smaller and the buffer not completely lost when adjusted to them, so the points are also included in the North tile, where they (rounded to y=4096 in MVT coordinates, i.e. in the South border) are kept by our filtering. (Y >= -1, that's OK)

But, why was it working with point-grid placement?

In that case, the aggregated coordinates are not the original tiny Y negative value, but a larger value, that of the center of the aggregation cell.

So it is no longer snapped to MVT 0, but retains a small positive value (namely 8) and the now pass our (E) filter. (Y < +1 FINE!)

So, will everything work fine when buffer adjustment is fixed?

Sure! what could go wrong?

Seriously, this is the situation:

If we were to use `buffersize=0` (no tile buffers), Maps API guarantees no duplicate points across tiles in that case, but due to the MVT coordinate snapping and our filtering, as described above, we might loss points. In that case we should change our filtering to `-1 <= X,Y <= +1` instead of `-1 <= X,Y < +1` (including all borders) and rely on Maps API to avoid duplicates.

But we now use a small buffer, `buffersize=1` because of our polygon-stroking algorithm.

So we can have redundant features across tiles and we must retain our `-1 <= X,Y < +1` filtering. 

As long as MVT coordinate snapping is done consistently in all tiles and the buffer adjustment keeps the buffer correctly, this should work perfectly with no duplicate or missing points.

Famous last words... so we'll probably meet again in another equatorial points issue, see you there!

**Comment by rochoa** [comment]
@skgsergio, this seems to be OK now.

Most likely due to the usage of PostGIS' ST_AsMVT instead of Mapnik.

Can we close it?

**Comment by Algunenano** [comment]
I think that the idea of being able to disable aggregations in CartoVL mentioned in https://github.com/CartoDB/carto-vl/issues/922#issuecomment-419046852 it's still worth it by itself, even if in the future we make the 'Smart backend' clever enough to disable aggregations based on the number of unique values.

Should I create an issue with the feature request?

**Comment by skgsergio** [comment]
From my user point of view, this is solved and can be closed. But I see a very interesting talk here as @Algunenano pointed so proceed as you please.

**Comment by rochoa** [comment]
@Algunenano, true that.

> Should I create an issue with the feature request?

Please, do so.

**Comment by Algunenano** [comment]
I've opened https://github.com/CartoDB/carto-vl/issues/1142
