### ISSUE TITLE
Get feature object by ID

### ISSUE THREAD

**Issue by Jesus89** [CartoDB/carto-vl#959]
Sometimes is useful to obtain the feature object (https://carto.com/developers/carto-vl/reference/#feature) by ID. Now the only way to get a feature is in the interactivity callbacks, but what if you want to style a feature but without interact directly with it?

To solve this case it would be nice to have an API to access the features. Here are some approach proposals.

### Add features array to viz

```js
const viz = new carto.Viz();
const myFeature = viz.features.find(x => x.id === ID);
myFeature.color.blendTo('red');
myFeature.color.reset();
// The same as in the interactivity `event.features`
// but without the feature reference to viz
```

### Add features object to viz

```js
const viz = new carto.Viz();
const myFeature = viz.features[ID];
myFeature.color.blendTo('red');
myFeature.color.reset();
```

### Add getFeature function to viz

```js
const viz = new carto.Viz();
const myFeature = viz.getFeature(ID);
myFeature.color.blendTo('red');
myFeature.color.reset();
```

**Comment by Jesus89** [comment]
As proposed by @elenatorro here: https://github.com/CartoDB/carto-vl/issues/954#issuecomment-421942910, `viewportFeatures` could be used to get the array of features. In this case, we would need `globalFeatures`.

However, I think this approach is less nice than the other ones from the user point of view.

```js
const viz = new carto.Viz(`
  @features: globalFeatures()
`);
const myFeature = viz.variables.features.value.find(x => x.id === ID);
// OR const myFeature = viz.variables.features[ID];
myFeature.color.blendTo('red');
myFeature.color.reset();
```

**Comment by rochoa** [comment]
Do you want to get the feature or do you want to style the feature by its id property?

**Comment by rochoa** [comment]
Not the biggest expert here, but what about using "blend"?

```js
const source = new carto.source.SQL(`
    SELECT cartodb_id, category, ST_Transform(ST_SetSRID(geom, 4326), 3857) AS the_geom_webmercator
    FROM (VALUES
        (1, 'car', ST_MakePoint(-10, 40)),
        (2, 'bus', ST_MakePoint(0, 40)),
        (3, 'bicycle', ST_MakePoint(10, 40))
    ) AS t (cartodb_id, category, geom)
`);
const viz = new carto.Viz(`
    width: 20
    strokeWidth: 0
    color: blend(
        ramp(buckets($category, ['car', 'bus']), [red, green], blue),
        black,
        false
    )
`);
```

Later you change the blend's `mix` with:

```js
viz.color.mix.blendTo('$cartodb_id == 1', 1000)
```

![blendto](https://user-images.githubusercontent.com/45346/46757954-e5c32900-cccb-11e8-96d5-63bfaada798f.gif)


cc @davidmanzanares

**Comment by davidmanzanares** [comment]
Getting the feature object by ID doesn't seem like a common use case to me.

To do that you need the object ID, and that can come (I think) from 3 places:
- Externally to CVL. This seems so error prone and complicated that I think it would require to think first about why does it come from an external source.
- From a CVL feature object ID, in this case, just don't lose the object instead of only storing the ID.
- From a CVL feature property that references another feature. I think this won't work due to aggregations.


Regarding globalFeatures, that can be implemented, but using that will force to download all data to the client. Making tiling and the "smart backend" useless. Before doing that, I would think about how many data do you expect to have.

Honestly, to have 100 markers in a map, CVL is not the best technology, and our backend is not the right one either.

However, if you want to scale...

**Comment by VictorVelarde** [comment]
@Jesus89 We have added an example of blend with that very same IF use to the new guide on aggregations (WIP)

**Comment by rochoa** [comment]
@Jesus89, we already released the new guides with the changes @VictorVelarde commented.

We also changed `viewportFeatures` to return _features_ with the same capabilities as in interactivity features, see https://github.com/CartoDB/carto-vl/pull/1085.

I think that's enough to close this issue. Otherwise, reopen it.
