### ISSUE TITLE
Embed examples in guides

### ISSUE THREAD

**Issue by rochoa** [CartoDB/carto-vl#980]
This might require changes in the "Developers centre" code base.

**Comment by elenatorro** [comment]
AFAIK, this can be done by:

[Live Example](link to the files)

But I have to test it.

**Comment by elenatorro** [comment]
I have tested it locally and we do not need to change the developers center codebase for basic maps. . In order to embed an example, we can just use an iframe tag, and there is already an "example-map" class we can use to wrap the iframe in a container. We only need to be a bit consistent with the embed examples (like, give them a unique id, use always the same size, etc)

```html
<div class="example-map">
    <iframe 
        src="https://carto.com/developers/carto-vl/examples/maps/guides/getting-started/basicStyling.html" 
        width="100%"
        height="500" 
        frameBorder="0">
    </iframe>
</div>
```
We could change the codebase if we want / need to create something like having two maps together to compare them, which can be done by adding some CSS.
